preferred_syntax = :sass
http_path = '/'
css_dir = 'assets/css'
# sass_dir = 'assets/sass'
images_dir = 'assets/images'
javascripts_dir = 'assets/scripts'
relative_assets = true
line_comments = false
# output_style = :compressed
